- app/src/main/java/com/android/mediproject/MainActivity.kt
- app/src/main/java/com/android/mediproject/MainViewModel.kt
- app/src/main/java/com/android/mediproject/MediApplication.kt
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/navigation/main_nav.xml
- core/ui/src/main/java/com/android/mediproject/core/ui/base/BaseActivity.kt
- core/ui/src/main/res/values/string.xml
- feature/community/src/main/java/com/android/mediproject/feature/community/CommunityFragment.kt
- feature/home/src/androidTest/java/com/android/mediproject/feature/home/ExampleInstrumentedTest.kt
- feature/home/src/main/java/com/android/mediproject/feature/home/HomeFragment.kt
- feature/home/src/main/java/com/android/mediproject/feature/home/HomeViewModel.kt
- feature/home/src/main/res/layout/fragment_home.xml
- feature/home/src/main/res/navigation/home_nav.xml
- feature/home/src/test/java/com/android/mediproject/feature/home/ExampleUnitTest.kt
- feature/intro/src/main/java/com/android/mediproject/feature/intro/IntroFragment.kt
- feature/intro/src/main/java/com/android/mediproject/feature/intro/SignUpViewModel.kt
- feature/intro/src/main/java/com/android/mediproject/feature/intro/SingUpFragment.kt
- feature/intro/src/main/res/layout/fragment_intro.xml
- feature/intro/src/main/res/navigation/intro_nav.xml
- feature/mypage/src/main/java/com/android/mediproject/feature/mypage/MyPageFragment.kt
- feature/setting/src/main/java/com/android/mediproject/feature/setting/SettingFragment.kt
- feature/splash/src/main/java/com/android/mediproject/feature/splash/SplashFragment.kt
<h2> ⚒️ 작업 내용 </h2>
- fun handelEvent -> fun handleEvent 오타 수정
- BottomNavigationView visibility 관련 로직 추가
<h2>🧩기타 사항 </h2>
> #5/feat/bottom navigation visibility logic

- core/ui/src/main/java/com/android/mediproject/core/ui/base/view/Bar.kt
- core/ui/src/main/java/com/android/mediproject/core/ui/base/view/SettingBar.kt
- core/ui/src/main/res/drawable/right_arrow.xml
- core/ui/src/main/res/layout/bar.xml
- core/ui/src/main/res/layout/settingbar.xml
- core/ui/src/main/res/values/attrs.xml
- core/ui/src/main/res/values/color.xml
- feature/intro/src/main/java/com/android/mediproject/feature/intro/IntroViewModel.kt
- feature/setting/src/main/java/com/android/mediproject/feature/setting/SettingFragment.kt
- feature/setting/src/main/java/com/android/mediproject/feature/setting/SettingViewModel.kt
- feature/setting/src/main/res/layout/fragment_setting.xml
- feature/setting/src/main/res/values/string.xml
- feature/setting/src/main/res/values/strings.xml
closed #25 
- 설정 화면 구현
- 설정 화면 클릭 시 이어지는 노션 사이트 틀 구성
- 버튼과 연결
- 각 ViewModel에서 이벤트 보낼 때 함수 구조 약간 변경
ex)
fun notice(){event(SettingEvent.Notice())} 에서,
fun notice() = event(SettingEvent.Notice()) 로 변경
> #25/feature/tgyuu/setting

- package-lock.json
- server/README.md
- server/bin/www.js
- server/package-lock.json
- server/package.json
- server/src/config/jwt.js
- server/src/config/sequelize.js
- server/src/controller/user/user.ctrl.js
- server/src/models/test.js
- server/src/models/user.js
- server/src/routes/home/index.js
- server/src/routes/user/userRouter.js
closed #37
JWT 기반 인증, 인가를 제공하기 위한 미들웨어 및 기능들을 구현하였습니다.
브이
화이팅
> #37/feature/juno/jwt

- server/app.js
- server/package-lock.json
- server/package.json
- server/src/config/jwt.js
- server/src/config/responseMsg.js
- server/src/controller/user/user.ctrl.js
- server/src/models/user.js
- server/src/service/userService.js
closed #22
회원가입 기능을 구현하였습니다.
치즈
화이팅
> #22/feature/juno/sign up

- server/src/config/jwt.js
- server/src/config/response.js
- server/src/config/responseMsg.js
- server/src/controller/user/user.ctrl.js
- server/src/models/user.js
- server/src/routes/user/userRouter.js
- server/src/service/userService.js
#21 
로그인 기능을 구현하였습니다.
해당 pr의 logic과 관련된 사항은 아니나, 종료 커맨드(close, closed, etc...)를 통해 issue를 닫기 위해서는 pr이 repository의 main branch를 대상으로 할 때에만 가능하다는 점을 알게 되었습니다.
> #21/feature/juno/sign in

- server/src/config/jwt.js
- server/src/config/responseMsg.js
- server/src/controller/user/user.ctrl.js
- server/src/routes/user/userRouter.js
- server/src/service/userService.js
#43 
Access token 만료 시 refresh token을 기반으로 access token과 refresh token을 재발급하는 기능을 구현하였습니다.
> #43/feature/juno/reissue token

- feature/news/src/main/res/layout/fragment_news.xml
> fix newsFragment Bar Id

- feature/camera/src/main/res/layout/fragment_detected_image_dialog.xml
- feature/camera/src/main/res/layout/item_view_detected_object.xml
- feature/search/src/main/res/layout/manual_medicine_item.xml
closes #56 
bindingAdapter 관련 에러 해결
-
-
> #56 fix bindingAdapter관련 기존 xml에서 사용하고 있던 imgUrl과 같은 속성을 img로 통일

- app/src/main/res/navigation/main_nav.xml
- core/ui/src/main/java/com/android/mediproject/core/ui/base/view/Bar.kt
- feature/intro/src/main/java/com/android/mediproject/feature/intro/IntroFragment.kt
- feature/search/src/main/res/layout/fragment_manual_search_result.xml
- feature/search/src/main/res/layout/fragment_search_medicines.xml
closes #40 
- 앱 전반적으로 사용하는 Bar에 뒤로가기 버튼을 눌렀을 때의 로직을 추가합니다.
- 검색화면 상단에 Bar를 추가합니다.
<br><br>
생각보다 매우 간단했습니다
CustomBar 정의하는 클래스에 findNavController() 를 이용해서 popBackStack() 해주면 끝...!
> #40 feat 커스텀 바 뒤로가기 눌렀을 때 로직 추가

- core/ui/src/main/res/values/color.xml
- feature/mypage/build.gradle.kts
- feature/mypage/src/main/java/com/android/mediproject/feature/mypage/MyPageFragment.kt
- feature/mypage/src/main/java/com/android/mediproject/feature/mypage/MyPageViewModel.kt
- feature/mypage/src/main/java/com/android/mediproject/feature/mypage/mypagemore/MyPageMoreBottomSheetFragment.kt
- feature/mypage/src/main/java/com/android/mediproject/feature/mypage/mypagemore/MyPageMoreBottomSheetViewModel.kt
- feature/mypage/src/main/res/drawable/rectangle_20_main.xml
- feature/mypage/src/main/res/drawable/rectangle_20_white.xml
- feature/mypage/src/main/res/layout/fragment_my_page.xml
- feature/mypage/src/main/res/layout/fragment_my_page_more_bottom_sheet.xml
- feature/mypage/src/main/res/values/strings.xml
- feature/mypage/src/main/res/values/styles.xml
closes #94 
마이 페이지에서 더보기 눌렀을 시 바텀시트 올라오게 구현
바텀시트 각 아이템 클릭했을 시 이벤트 구현
완료 버튼 눌렀을 시 마이 페이지에서 콜백 받는 로직 구현
++아직 CallBack했을 때 띄우는 dialog는 구현하지 않았음.
https://github.com/pknu-wap/2023_1_WAP_APP_TEAM_MEDI/assets/116813010/beab862f-9dcb-4e1a-8914-740048bf5de0
<h3> BottomSheet 드래그 막는 로직 </h3>
```kotlin
override fun onCreateDialog(savedInstanceState: Bundle?): Dialog {
val bottomSheetDialog = super.onCreateDialog(savedInstanceState) as BottomSheetDialog
bottomSheetDialog.setOnShowListener {
val bottomSheet = bottomSheetDialog
.findViewById<FrameLayout>(com.google.android.material.R.id.design_bottom_sheet)
if (bottomSheet != null) {
val behavior: BottomSheetBehavior<*> = BottomSheetBehavior.from(bottomSheet)
behavior.isDraggable = false
}
}
return bottomSheetDialog
}
```
<br>
위 코드를 추가하면 바텀시트의 드래그를 막을 수 …
> #94/feature/tgyuu/my page more

- server/bin/www.js
- server/src/config/responseMsg.js
- server/src/controller/comment/index.js
- server/src/models/medicine.js
- server/src/routes/home/index.js
- server/src/routes/medicine/comment/index.js
- server/src/routes/medicine/index.js
- server/src/service/commentService.js
- server/src/service/medicineService.js
> #75/feature/comment crud

- server/src/controller/medicine/favorite/favorite.ctrl.js
- server/src/routes/medicine/favorite/index.js
- server/src/service/medicineService.js
#105 
관심 약 여부를 조회하는 기능을 개발하였습니다.
> #105 관심 약 여부 조회 기능 개발

- server/src/service/userService.js
#108 
토큰 재발급 API가 정상작동하지 않는 문제를 해결하였습니다.
> #108/fix/juno/fix reissue token

- server/src/config/responseMsg.js
- server/src/controller/user/user.ctrl.js
- server/src/routes/user/userRouter.js
- server/src/service/userService.js
#113 
유저 개인정보 관리 기능을 구현하였습니다.
1. 유저 닉네임 변경
2. 유저 비밀번호 변경
3. 회원 탈퇴
> #113/feature/juno/user info management

- server/src/service/commentService.js
- server/src/service/userService.js
> #75 : UserService에 _getUserNickname 함수 추가

- server/src/routes/medicine/comment/index.js
#117 
의약품 ID 반환 API의 HTTP method를 POST로 변경했습니다.
> #117 의약품 ID 반환 API의 HTTP method POST로 변경

- server/src/service/userService.js
#124 
로그인, 회원가입 시 API 반환값에 유저 정보를 포함하였습니다.
유저 정보는 유저 id, nickname, email입니다.
> #124 로그인, 회원가입 API 반환값에 유저 정보 포함

- feature/comments/src/main/java/com/android/mediproject/feature/comments/mycommentslist/MyCommentsListFragment.kt
- feature/interestedmedicine/src/main/java/com/android/mediproject/feature/interestedmedicine/moreinterestedmedicine/MoreInterestedMedicineFragment.kt
- feature/intro/src/main/java/com/android/mediproject/feature/intro/LoginFragment.kt
- feature/intro/src/main/java/com/android/mediproject/feature/intro/SignUpFragment.kt
closes #131 
상단바 패딩 주는 나머지 Fragment들 노동했습니다.
> #131/feature/tgyuu/bar top padding

- server/src/controller/user/user.ctrl.js
- server/src/service/commentService.js
- server/src/service/userService.js
> [Hotfix]: tokenResponseFormat 수정

- server/src/controller/user/user.ctrl.js
- server/src/routes/user/userRouter.js
- server/src/service/commentService.js
> #129/feature/wino/get comment from token

- core/datastore/src/main/java/com/android/mediproject/core/datastore/AppDataStore.kt
- core/datastore/src/main/java/com/android/mediproject/core/datastore/AppDataStoreImpl.kt
- core/domain/src/main/java/com/android/mediproject/core/domain/user/UserUseCase.kt
- feature/mypage/src/main/java/com/android/mediproject/feature/mypage/MyPageViewModel.kt
- feature/mypage/src/main/java/com/android/mediproject/feature/mypage/mypagemore/MyPageMoreDialogFragment.kt
- feature/mypage/src/main/java/com/android/mediproject/feature/mypage/mypagemore/MyPageMoreDialogViewModel.kt
closes #139 
제곧내입니다.
로컬 토큰이 안밀려요
> #139/refactor/tgyuu/change nickname,withdrawale ehancement

- core/datastore/src/main/java/com/android/mediproject/core/datastore/TokenDataSourceImpl.kt
- core/datastore/src/main/java/com/android/mediproject/core/datastore/TokenServer.kt
> #139 refact removeTokens() 로직 보완

- core/ui/src/main/java/com/android/mediproject/core/ui/base/view/Bar.kt
- core/ui/src/main/res/values/attrs.xml
- core/ui/src/main/res/values/color.xml
- feature/medicine/src/main/java/com/android/mediproject/feature/medicine/main/MedicineInfoFragment.kt
- feature/medicine/src/main/res/layout/fragment_medicine_info.xml
> #147 add MedicineInfo TopBar Logic

- .idea/misc.xml
- app/src/main/java/com/android/mediproject/MainActivity.kt
- app/src/main/java/com/android/mediproject/MediApplication.kt
- core/common/src/main/java/com/android/mediproject/core/common/util/UriBuilder.kt
- core/data/src/main/java/com/android/mediproject/core/data/remote/granule/GranuleIdentificationRepositoryImpl.kt
- core/datastore/src/main/java/com/android/mediproject/core/datastore/TokenDataSourceImpl.kt
- core/model/src/main/java/com/android/mediproject/core/model/DataGoKrBaseResponse.kt
- core/model/src/main/java/com/android/mediproject/core/model/awscommon/BaseAwsQueryResponse.kt
- core/model/src/main/java/com/android/mediproject/core/model/awscommon/BaseAwsSignResponse.kt
- core/network/src/main/java/com/android/mediproject/core/network/InternetNetworkListener.kt
- core/network/src/main/java/com/android/mediproject/core/network/datasource/comments/CommentsListDataSourceImpl.kt
- core/network/src/main/java/com/android/mediproject/core/network/datasource/penalties/recallsuspension/RecallSuspensionListDataSourceImpl.kt
- core/ui/src/main/java/com/android/mediproject/core/ui/base/view/HeaderForElementsView.kt
- core/ui/src/main/java/com/android/mediproject/core/ui/base/view/MediSearchbar.kt
- feature/camera/src/main/java/com/android/mediproject/feature/camera/confirmdialog/ConfirmDialogFragment.kt
- feature/comments/src/main/java/com/android/mediproject/feature/comments/commentsofamedicine/MedicineCommentsViewModel.kt
- feature/comments/src/main/java/com/android/mediproject/feature/comments/mycommentslist/MyCommentsListViewModel.kt
- feature/comments/src/main/java/com/android/mediproject/feature/comments/recentcommentlist/RecentCommentListViewModel.kt
- feature/home/src/main/java/com/android/mediproject/feature/home/HomeViewModel.kt
- feature/intro/src/main/java/com/android/mediproject/feature/intro/SignUpViewModel.kt
- feature/mypage/src/main/java/com/android/mediproject/feature/mypage/mypagemore/MyPageMoreBottomSheetFragment.kt
- feature/news/src/main/java/com/android/mediproject/feature/news/NewsViewModel.kt
- feature/news/src/main/java/com/android/mediproject/feature/news/adminaction/AdminActionScreen.kt
- feature/news/src/main/java/com/android/mediproject/feature/news/recallsuspension/RecallSuspensionScreen.kt
- feature/search/src/main/java/com/android/mediproject/feature/search/recentsearchlist/RecentSearchListFragment.kt
- feature/search/src/main/java/com/android/mediproject/feature/search/result/ai/AiSearchResultViewModel.kt
- feature/setting/src/main/java/com/android/mediproject/feature/setting/SettingFragment.kt
#91
Android studio의 코드 자동 정리 기능을 사용해서 안쓰이는 코드 정리하였습니다
> #91 사용되지 않는 로직 정리

- app/src/main/res/layout/activity_main.xml
> #152 add 개발버전 워터마크 추가

- core/ui/src/main/java/com/android/mediproject/core/ui/base/BaseFragment.kt
- feature/mypage/src/main/java/com/android/mediproject/feature/mypage/MyPageFragment.kt
closes #158 
- 불필요한 주석 제거
-- 주석을 최대한 쓰지 말 것. 함수 명을 주석처럼 직관적 이게 잘 지으면 모든 것이 해결 된다.
-- If 조건문에 걸리는 분기 문은 함수로 빼서 해당 함수의 작명을 직관적으로 잘 지으면 된다. 
- 하나의 함수 최대한 하나의 역할만 하도록 수정
- 함수 및 변수 명 직관적인 이름으로 변경
- 조건문에 있는 내용 함수로 빼서 더 직관적으로 읽을 수 있게 변경
- 코드가 위에서 아래로 책 읽듯이 술술 읽히도록 함수 위치 조정
- 반복되는 코드 최대한 재 사용할 수 있도록 변경
- 위에서 밑으로 갈수록 추상화 레벨이 낮아지도록 변경
-
-
> #158/refactor/tgyuu/my page fragment

- .editorconfig
- build-logic/gradle.properties
- build.gradle.kts
- core/domain/src/main/java/com/android/mediproject/core/domain/GetMedicineApprovalListUseCase.kt
- core/network/src/main/java/com/android/mediproject/core/network/module/DataGoKrNetwork.kt
- detekt-config.yml
- feature/favoritemedicine/src/main/java/com/android/mediproject/feature/favoritemedicine/FavoriteMedicineFragment.kt
- feature/favoritemedicine/src/main/java/com/android/mediproject/feature/favoritemedicine/favoritemedicinemore/FavoriteMedicineMoreFragment.kt
- feature/favoritemedicine/src/main/java/com/android/mediproject/feature/favoritemedicine/favoritemedicinemore/recyclerview/FavoriteMeidicneMoreAdapter.kt
- gradle.properties
- gradle/libs.versions.toml
#162 
- 라이브러리 업데이트
- ktlint, detekt 적용(컨벤션 동기화)
- gradle 빌드 설정 추가
- 수정되지 않은 파일명 수정
> #162/update/jsp/lib update

- app/src/main/java/com/android/mediproject/MainActivity.kt
- feature/comments/src/main/java/com/android/mediproject/feature/comments/commentsofamedicine/MedicineCommentsViewModel.kt
- feature/comments/src/main/java/com/android/mediproject/feature/comments/mycommentslist/MyCommentsListFragment.kt
- feature/comments/src/main/java/com/android/mediproject/feature/comments/recentcommentlist/RecentCommentListFragment.kt
- feature/etc/src/main/java/com/android/mediproject/feature/etc/EtcFragment.kt
- feature/mypage/src/main/java/com/android/mediproject/feature/mypage/MyPageFragment.kt
closes #170
Comment, Etc 모듈 리팩터링
MedicineCommentsFragment 는 준성님이 작업하신 곳이라 제가 모르는 코드들이 많아 냅뒀습니다...!
추후에 부탁드려요!
> #170/refactor/tgyuu/comment etc refactoring

- core/common/src/main/java/com/android/mediproject/core/common/uiutil/EditableUtil.kt
- core/common/src/main/java/com/android/mediproject/core/common/util/RegexChecker.kt
- core/data/src/main/java/com/android/mediproject/core/data/remote/sign/SignRepository.kt
- core/data/src/main/java/com/android/mediproject/core/data/remote/sign/SignRepositoryImpl.kt
- core/domain/src/main/java/com/android/mediproject/core/domain/sign/SignUseCase.kt
- core/model/src/main/java/com/android/mediproject/core/model/requestparameters/LoginParameter.kt
- core/network/src/main/java/com/android/mediproject/core/network/datasource/sign/SignDataSource.kt
- core/network/src/main/java/com/android/mediproject/core/network/datasource/sign/SignDataSourceImpl.kt
- core/network/src/main/java/com/android/mediproject/core/network/module/AwsNetwork.kt
- core/ui/src/main/java/com/android/mediproject/core/ui/base/BaseFragment.kt
- feature/intro/src/main/java/com/android/mediproject/feature/intro/IntroFragment.kt
- feature/intro/src/main/java/com/android/mediproject/feature/intro/IntroViewModel.kt
- feature/intro/src/main/java/com/android/mediproject/feature/intro/LoginFragment.kt
- feature/intro/src/main/java/com/android/mediproject/feature/intro/LoginViewModel.kt
- feature/intro/src/main/java/com/android/mediproject/feature/intro/SignUpFragment.kt
- feature/intro/src/main/java/com/android/mediproject/feature/intro/SignUpViewModel.kt
- feature/intro/src/main/res/layout/fragment_login.xml
- feature/mypage/src/main/java/com/android/mediproject/feature/mypage/MyPageFragment.kt
- feature/mypage/src/main/java/com/android/mediproject/feature/mypage/mypagemore/MyPageMoreDialogFragment.kt
closes #173 
- Intro 모듈 전반적인 리팩토링
> #173/refactor/tgyuu/intro refactoring

- app/src/main/java/com/android/mediproject/MainActivity.kt
- core/common/src/main/java/com/android/mediproject/core/common/uiutil/SystemBarColorAnalyzer.kt
- core/common/src/main/java/com/android/mediproject/core/common/util/DelayEditTextWatcher.kt
- core/data/src/main/java/com/android/mediproject/core/data/remote/sign/SignRepository.kt
- core/data/src/main/java/com/android/mediproject/core/data/remote/sign/SignRepositoryImpl.kt
- core/database/src/main/java/com/android/mediproject/core/database/cache/DataCacheDao.kt
- core/database/src/main/java/com/android/mediproject/core/database/cache/MedicineDetailCacheDao.kt
- core/database/src/main/java/com/android/mediproject/core/database/cache/MedicineImageCacheDao.kt
- core/database/src/main/java/com/android/mediproject/core/database/cache/manager/DataCacheManager.kt
- core/database/src/main/java/com/android/mediproject/core/database/cache/manager/MedicineDataCacheManagerImpl.kt
- core/domain/src/main/java/com/android/mediproject/core/domain/GetMedicineApprovalListUseCase.kt
- core/network/src/main/java/com/android/mediproject/core/network/datasource/image/GoogleSearchDataSourceImpl.kt
- core/network/src/main/java/com/android/mediproject/core/network/datasource/medicineapproval/MedicineApprovalDataSourceImpl.kt
- core/network/src/main/java/com/android/mediproject/core/network/datasource/sign/SignDataSource.kt
- core/network/src/main/java/com/android/mediproject/core/network/datasource/sign/SignDataSourceImpl.kt
- core/network/src/main/java/com/android/mediproject/core/network/datasource/tokens/NewTokens.kt
- core/network/src/main/java/com/android/mediproject/core/network/datasource/tokens/TokenDataSourceImpl.kt
- core/network/src/main/java/com/android/mediproject/core/network/datasource/tokens/TokenResponseInterceptor.kt
- core/network/src/main/java/com/android/mediproject/core/network/module/AwsNetwork.kt
- core/network/src/main/java/com/android/mediproject/core/network/module/DataGoKrNetwork.kt
- core/network/src/main/java/com/android/mediproject/core/network/module/NetworkModule.kt
- core/network/src/main/java/com/android/mediproject/core/network/parameter/LoginRequestParameter.kt
- core/network/src/main/java/com/android/mediproject/core/network/parser/HtmlParser.kt
- core/network/src/main/java/com/android/mediproject/core/network/tokens/TokenRequestInterceptor.kt
- core/network/src/main/java/com/android/mediproject/core/network/tokens/TokenServer.kt
- core/network/src/main/java/com/android/mediproject/core/network/tokens/TokenServerImpl.kt
- core/ui/src/main/java/com/android/mediproject/core/ui/base/BaseFragment.kt
- feature/camera/src/main/java/com/android/mediproject/feature/camera/MedicinesDetectorFragment.kt
- feature/intro/src/main/java/com/android/mediproject/feature/intro/LoginFragment.kt
- feature/intro/src/main/java/com/android/mediproject/feature/intro/LoginViewModel.kt
#180
#171 
#178
1.  시스템 바 색상 갱신 로직 개선
2.  약 사진 구글 검색하는 데 쓰이는 스레드 변경
3.  불필요한 주석 제거
4.  로그인 시 이메일/비밀번호 입력 여부 실시간 확인하는 로직 수정
> #180/refactor/jsp/systembar etc

- core/common/src/main/java/com/android/mediproject/core/common/mapper/MedicineInfoMapper.kt
- core/common/src/main/res/values/color.xml
- core/common/src/main/res/values/strings.xml
- feature/mypage/src/main/java/com/android/mediproject/feature/mypage/mypagemore/MyPageMoreBottomSheetFragment.kt
- feature/penalties/src/main/java/com/android/mediproject/feature/penalties/recentpenaltylist/RecentPenaltyListFragment.kt
- feature/penalties/src/main/java/com/android/mediproject/feature/penalties/recentpenaltylist/RecentPenaltyListViewModel.kt
- feature/penalties/src/main/res/layout/fragment_recent_penalty_list.xml
closes #184
penalties 모듈 리팩토링
News 모듈하고 병합하는건 다른 이슈에서 할게욥
viewModel에서 context(안드로이드 의존성) 없앴습니다.
> #184/refactor/tgyuu/penalties refactoring

- core/ui/src/main/res/values/dimens.xml
- feature/favoritemedicine/build.gradle.kts
- feature/favoritemedicine/src/main/java/com/android/mediproject/feature/favoritemedicine/FavoriteMedicineFragment.kt
- feature/favoritemedicine/src/main/java/com/android/mediproject/feature/favoritemedicine/FavoriteMedicineViewModel.kt
- feature/favoritemedicine/src/main/java/com/android/mediproject/feature/favoritemedicine/favoritemedicinemore/FavoriteMedicineMoreFragment.kt
- feature/favoritemedicine/src/main/java/com/android/mediproject/feature/favoritemedicine/favoritemedicinemore/FavoriteMedicineMoreViewModel.kt
- feature/favoritemedicine/src/main/java/com/android/mediproject/feature/favoritemedicine/favoritemedicinemore/recyclerview/FavoriteMeidicneMoreAdapter.kt
- feature/favoritemedicine/src/main/res/layout/fragment_favorite_medicine.xml
- feature/favoritemedicine/src/main/res/layout/fragment_favorite_medicine_more.xml
- feature/mypage/src/main/res/layout/fragment_my_page.xml
closes #207 
FavoriteMedicine 모듈도 반복작업 했어요..!
> #207/feature/tgyuu/favorite medicine UI state wrapping

- server/app.js
- server/bin/www.js
- server/package-lock.json
- server/package.json
- server/src/config/multer.js
- server/src/config/staticDirLoc.js
- server/src/controller/user/user.ctrl.js
- server/src/models/user.js
- server/src/routes/user/userRouter.js
- server/src/service/userService.js
#203 
프로필 사진 기능 추가로 인해, 유저 관련 API에 업로드 이미지 관리 로직들을 추가하였습니다.
> #203/feature/juno/user profile image
